### ISSUE TITLE
About the purpose of Webflux

### ISSUE THREAD

**Issue by HelloTo4x** [valb3r/time-tracker#69]
Hi, i am reading your project, can u tell me the purpose of Webflux, reactive in your project ? Is it for increasing performance, can u tell me some disadvantaged of Webflux ?

**Comment by valb3r** [comment]
@HelloTo4x Hi, 
> can u tell me the purpose of Webflux, reactive in your project ? Is it for increasing performance

Yes. Mostly it is for less memory consumption under heavy load and better throughput under heavy concurrency conditions. Under **low-to-medium load** there are no explicit advantages especially then comparing to Servlet 3.0 spec with Controllers that return Future-based results

> can u tell me some disadvantaged of Webflux ?
Readability is not good - implementing complex business logic with zip's and map's is complicated and resulting code is hard to read and understand. Joining results from different sources by some key is hard to read. But for simple cases, more or less OK. Also there was a need for JDK installed (instead of JRE) to get meaningful stack traces of an error - but this was solved via javaagent now.

**Comment by HelloTo4x** [comment]
thank u so much <3
